# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DeleteFiles@1
  inputs:
    Contents: 'adb_binary'

- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/zsh2401/AutumnBox-AdbBinaries-Store.git adb_binary -q'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    filePath: 'scripts/build_canary.ps1'

- task: AppCenterDistribute@3
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    serverEndpoint: 'AppCenter'
    appSlug: 'Autumn2077/AutumnBox'
    appFile: 'archive.zip'
    buildVersion: '$(Build.SourceVersion)'
    releaseNotesOption: 'input'
    releaseNotesInput: '$(Build.SourceVersionMessage)'
    destinationType: 'groups'
    distributionGroupId: '41f1b280-60af-43da-8a90-b06940e8babc'

- task: AppCenterDistribute@3
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  inputs:
    serverEndpoint: 'AppCenter'
    appSlug: 'Autumn2077/AutumnBox'
    appFile: 'archive.zip'
    buildVersion: '$(Build.SourceVersion)'
    releaseNotesOption: 'input'
    releaseNotesInput: '$(Build.SourceVersionMessage)'
    destinationType: 'groups'
    distributionGroupId: '4f967e87-b760-4a38-87a5-495daccb7cb5'